package com.aajeevika.clf.model.data_model

data class ProductDetailDataModel(
    val productdetail: ProductDetails,
)

data class ProductDetails(
    val id: String,
    val categoryId: String,
    val product_id_d: String,
    val subcategoryId: String,
    val material_id: String,
    val template_id: String,
    val qty: String,
    val price: String,
    val name: String,
    val template_name: String,
    val localname_en: String,
    val localname_kn: String,
    val des_en: String,
    val des_kn: String,
    val description: String,
    val image_1: String?,
    val image_2: String?,
    val image_3: String?,
    val image_4: String?,
    val image_5: String?,
    val video_url: String?,
    val catName: String,
    val SubCatName: String,
    val length: String?,
    val width: String?,
    val height: String?,
    val vol: String?,
    val weight: String?,
    val length_unit: String?,
    val width_unit: String?,
    val height_unit: String?,
    val weight_unit: String?,
    val price_unit: String?,
    val vol_unit: String?,
    val certificate_data: ProductCertificateData?,
)

data class ProductCertificateData(
    val certificate_image_1: String?,
    val certificate_status_1: Int?,
    val certificate_type_1: Int?,
    var certificate_type_name_1: String?,
    val certificate_image_2: String?,
    val certificate_status_2: Int?,
    val certificate_type_2: Int?,
    var certificate_type_name_2: String?,
    val certificate_image_3: String?,
    val certificate_status_3: Int?,
    val certificate_type_3: Int?,
    var certificate_type_name_3: String?,
    val certificate_image_4: String?,
    val certificate_status_4: Int?,
    val certificate_type_4: Int?,
    var certificate_type_name_4: String?,
    val certificate_image_5: String?,
    val certificate_status_5: Int?,
    val certificate_type_5: Int?,
    var certificate_type_name_5: String?,
    val certificate_image_6: String?,
    val certificate_status_6: Int?,
    val certificate_type_6: Int?,
    var certificate_type_name_6: String?,
    val certificate_image_7: String?,
    val certificate_status_7: Int?,
    val certificate_type_7: Int?,
    var certificate_type_name_7: String?,
)
